fbs_teams = [
    "Georgia",
    "Kentucky",
    "Florida",
    "South Carolina",
    "Missouri",
    "Vanderbilt",
    "Tennessee",
    "Alabama",
    "Louisiana State",
    "Auburn",
    "Texas A&M",
    "Mississippi State",
    "Mississippi",
    "Arkansas",
    "Oklahoma",
    "West Virginia",
    "Texas",
    "Oklahoma State",
    "Baylor",
    "Texas Christian",
    "Texas Tech",
    "Kansas",
    "Kansas State",
    "Iowa State",
    "Ohio State",
    "Michigan",
    "Maryland",
    "Michigan State",
    "Indiana",
    "Penn State",
    "Rutgers",
    "Wisconsin",
    "Purdue",
    "Northwestern",
    "Iowa",
    "Minnesota",
    "Illinois",
    "Nebraska",
    "Clemson",
    "North Carolina State",
    "Boston College",
    "Syracuse",
    "Florida State",
    "Wake Forest",
    "Louisville",
    "Miami (FL)",
    "Virginia Tech",
    "Virginia",
    "Pittsburgh",
    "North Carolina",
    "Duke",
    "Georgia Tech",
    "Stanford",
    "Washington",
    "Oregon",
    "Washington State",
    "California",
    "Oregon State",
    "Colorado",
    "Southern California",
    "Arizona State",
    "Arizona",
    "Utah",
    "UCLA",
    "Liberty",
    "Massachusetts",
    "New Mexico State",
    "Notre Dame",
    "Army",
    "Brigham Young",
    "Cincinnati",
    "South Florida",
    "Central Florida",
    "Temple",
    "East Carolina",
    "Connecticut",
    "Southern Methodist",
    "Tulane",
    "Navy",
    "Memphis",
    "Tulsa",
    "Houston",
    "Boise State",
    "Utah State",
    "Wyoming",
    "Air Force",
    "Colorado State",
    "New Mexico",
    "Hawaii",
    "Nevada",
    "San Jose State",
    "Fresno State",
    "San Diego State",
    "Nevada-Las Vegas",
    "Appalachian State",
    "Georgia Southern",
    "Coastal Carolina",
    "Troy",
    "Georgia State",
    "South Alabama",
    "Arkansas State",
    "Louisiana-Monroe",
    "Louisiana",
    "Texas State",
    "Buffalo",
    "Miami (OH)",
    "Bowling Green State",
    "Kent State",
    "Akron",
    "Ohio",
    "Western Michigan",
    "Ball State",
    "Northern Illinois",
    "Eastern Michigan",
    "Central Michigan",
    "Toledo",
    "Marshall",
    "Florida International",
    "Middle Tennessee State",
    "Charlotte",
    "Florida Atlantic",
    "Old Dominion",
    "Western Kentucky",
    "Louisiana Tech",
    "Alabama-Birmingham",
    "Southern Mississippi",
    "Texas-San Antonio",
    "North Texas",
    "Rice",
    "Texas-El Paso",
]
